[build]
  publish = "dist"                   # Vite build output map
  functions = "netlify/functions"   # Map voor Netlify Functions
  command = "npm run build"         # Build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
